### ISSUE TITLE
Problem with "Run as administrator"

### ISSUE THREAD

**Issue by ITManLNK** [cluberti/VDI#6]
I tried the Windows 10 version, and it works fantastic except that I no longer have the ability to do “run as administrator” from the start menu, it appears that consent.exe fires but it never pops up on the screen. It is running in task manager but never opens on screen.

It also seems to have issue with shutdown, if you say restart it instantly goes to spinning circle and Please wait that is displayed normally after logging on.

I am attempting to use this on the Enterprise anniversary update version. Any ideas which option could be raising problems with the “run as” function?

**Comment by weldrake13** [comment]
hey, I have been using a variation of this script in production since Anniversary edition came out. I did a lot of testing initially and didnt find any Issues with run as administrator (and i was using that regularly with powershell). I was using build 1607 instead of an updated previous build. 
I have found that in the past (pre script) the run as option sometimes doesn't appear until after you have first launched the program. 
Looking at the script the only issue I encountered was that disabling the device association service in Win 10 enterprise (anniversary only) causes log on times to jump to 10 minutes plus as soon as the machine is domain joined.

**Comment by ITManLNK** [comment]
That's weird, as I have a fresh install of 1607 that is doing it.

Its a clean install from this media: 
SW_DVD5_WIN_ENT_10_1607_64BIT_English_MLF_X21-07102.ISO

You said a variation of the script, can you tell me whats different?

Do you have the machine in the domain when you run the script?  Mine is 
not, it is just standalone at this point.

I think I have that service still being disabled so that could be why a 
couple times I thought it hung on boot up/log in.

I will comment that out and try again.

Thanks
Paul

---

Paul Kramer
Manager
Information Systems

Kawasaki Motors Mfg. Corp.
6600 NW 27th St.
Lincoln, NE 68524

Email:   pkramer@lcn.kmmfg.com
Phone:   (402) 476-6600 (x1350)
Fax:   (402) 476-6672

This E-mail address is to be used for business purposes only. Do not send 
any E-mail messages to this address that do not have a specific business 
purpose. Thank you.
