### ISSUE TITLE
Running windows update in it's own process can cause it to fail

### ISSUE THREAD

**Issue by iangregory** [cluberti/VDI#9]
`sc.exe config wuauserv type= own` can cause Windows Update to fail to find updates, giving the error "There were some problems installing updates, but we’ll try again later. If you keep seeing this and want to search the web or contact support for information, this may help: (0x80070006)"

I had this issue and resolved it by switching the windows update service back to shared as described in this link:  https://answers.microsoft.com/en-us/windows/forum/windows_10-update/there-were-some-problems-installing-updates/8116d20a-4151-4132-9b91-ac0d6ae2d559?page=2#LastReply

The VDI script shouldn't change this from the default.

**Comment by cluberti** [comment]
While I don't doubt you resolved your issue by moving WU back into it's shared svchost, I run this service this way daily on hundreds of devices without failure, so I'd wager this is something else failing with WU as a victim.  We need more data to determine your failure scenario if you want help, otherwise commenting the change in your own usage is fine too.
